### ISSUE TITLE
Restore drag-and-drop firmare update.

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-code#1020]
Since we introduced the firmware install dialog, there is no longer a way to drag-and-drop firmware.zip files from CI in Pybricks code.

We still have `pybricksdev` to flash experimental builds, but it would be nice if we had drag-and-drop to make it easier for users to test the latest bug fix of an issue they are interested in.

**Comment by laurensvalk** [comment]
Based on discussions over the past few weeks, this seems like it would be quite useful. It makes it easy for users to test all the new functionality we've been introducing, and fixes thereof after reporting problems.

Is it a big change to add this back in?

UI-wise, perhaps we could allow dragging it onto the `Install Pybricks Firmware` button, or just anywhere in the settings pane.
