### ISSUE TITLE
[Bug] code.pybricks.com without Internet connection

### ISSUE THREAD

**Issue by GianCann** [pybricks/pybricks-code#117]
Without Internet connection, the program is not loaded to the hub.

The BLE connection work well, and show the output of the hub (if you run the main.py built-in), but is not possible to load a new program.

**Comment by dlech** [comment]
We are currently using `fetch()` to get the mpy-cross `.wasm` file. This needs to be changed so that it is available offline.

**Comment by dlech** [comment]
Actually, I guess we are using `fetch()` to get the firmware zip files, so that needs to be look into as well. The `.wasm` file is handled by code automatically generated by Emscripten, so we need to investigate how that works too.

**Comment by dlech** [comment]
This should be fixed by https://github.com/pybricks/pybricks-code/commit/441d517a52c578a85e692cd9dc000ac1bc9d8d65

It looks like the .zip files are already properly cached.
