### ISSUE TITLE
[Bug] Error "`wasm streaming compile failed" running a python program on a movehub / Control+ hub

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/pybricks-code#124]
**Describe the bug**
Trying to run a stripped sample python program using [https://code.pybricks.com/](https://code.pybricks.com/)

**To reproduce**
1. On Windows 10 open Chrome version 85
2. Flash firmware to the hub (take a minute but seems to end OKE)
3. Click "Connect using bluetooth"
4. The button "Download and run" goes from light blue to dark blue (So is available)
5. Click  button "Download and run"
6. See error:
`wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.,falling back to ArrayBuffer instantiation,Traceback (most recent call last):, File "main.py", line 10, SyntaxError: invalid syntax`

**Expected behavior**
Run the python program 

**Screenshots**
![image](https://user-images.githubusercontent.com/8142081/87321668-d1f5c800-c52c-11ea-8369-bdbc629ba37b.png)

**Versions**
Google Chrome | 85.0.4183.16 (Official Build) dev (64-bit) (cohort: Dev-nonPGO)
Revision | e5f41a80568bb5f51f3468c3fbb92aac2fceab70-refs/branch-heads/4183@{#226}
Windows 10 OS Version 1909 (Build 18363.900)

`chrome://flags/#enable-experimental-web-platform-features`
 is **enabled**

**Comment by dlech** [comment]
Hi Bert!

An @GianCann mentioned, there is a syntax error in your program, but the error message reveals another bug.

The part about "wasm" is probably a side-effect of https://github.com/pybricks/pybricks-code/commit/441d517a52c578a85e692cd9dc000ac1bc9d8d65. I was actually surprised I didn't see something like this while testing.

**Comment by BertLindeman** [comment]
Ah that figures.
I was hit by the start of the error message, so went to search the web about how to change the MIME type.
But you direct me to the END of the error message.
I had more than one basic python typos.
After I corrected the syntax.....
It simply worked.

The bug was in my reading of the error.

![image](https://user-images.githubusercontent.com/8142081/87323971-c2c44980-c52f-11ea-8ce0-8865d1eb8958.png)

**Comment by GianCann** [comment]
@dlech  I seeing the "wasm" error part every time I have type wrong code, but I thinked that is part of the compiler warning.

**Comment by BertLindeman** [comment]
@dlech  @GianCann Thanks for the comments. So happy I do have a start with this.
Was getting comfortable with micropython on the Spike hub and micropython on the ev3.

The  "wasm" **did** confuse me. Would be less confusing if that part could be safely "dropped" ;-)

**Comment by dlech** [comment]
This should be fixed now (was a web server issue). You may have to clear your browser cache first before the "wasm" part of the error message goes away.

**Comment by BertLindeman** [comment]
@dlech you **are** fast ;-)

Used settings in chrome 85 to clear all data, and used F5 to refresh the session.
Could it be that there should be some refresh on the server side (or wait for propagation of the fix?) 
 
Stil get the error on a syntax error like this:

`wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': 
Incorrect response MIME type. 
Expected 'application/wasm'.,falling back to ArrayBuffer instantiation,Traceback (most recent call last):, 
File "main.py", line 2,SyntaxError: invalid syntax`

**Comment by dlech** [comment]
<kbd>F5</kbd> is not enough. <kbd>CTRL</kbd>+<kbd>F5</kbd> will clear the cache.

**Comment by BertLindeman** [comment]
Right you are ;-)

ctrl-f5 does the trick: Now get a well understood error:
`Traceback (most recent call last):, File "main.py", line 1,SyntaxError: invalid syntax`
