### ISSUE TITLE
yarn start time

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#1347]
Since we were both getting the feeling that `yarn start` was taking longer, I thought I'd measure it.

I don't really mind that it takes long, but I was curious to see if there was a trend.

---

Latest listed first, time in seconds. All are measured once or twice with an external stopwatch. In all cases, `yarn install` was run first (not included in time).

4c09c5470f90d3be3380335f144ee9f5363a9f04 - 32.5
0a47abe0920b7c0088c47e81159dd742b1dd48b2 - 27.2
1d9dd82191c2c136ffa6116e59241437b21cc492 - 30.5
072358036a27a7c8b3a50c64d7bfed57102eb838 - 46.9

-----

df0e9805d972744160fbdd9f50b9f9db3150e821 - 32.1

The last one listed is way back, before adding monaco editor.

So maybe it's just always been slow?

**Comment by dlech** [comment]
Yes, I think so. Maybe in a few years, webpack will be rewritten in rust and won't be so slow anymore.

**Comment by dlech** [comment]
Alternate solution. Get a new MacBook. My M1 Mac takes less than 5 seconds from yarn start to page loaded.
