### ISSUE TITLE
Python2 no longer required - Update Contributing.md

### ISSUE THREAD

**Issue by scmmmh** [pybricks/pybricks-code#1569]
I've just set up the dev environment myself, following the instructions in CONTRIBUTING.md. It all works perfectly, but you may want to update CONTRIBUTING.md to reflect that Python 2 no longer seems to be a necessity to get everything to build.

**Comment by dlech** [comment]
Thanks for pointing it out. Would you like to make a pull request to remove it?

**Comment by scmmmh** [comment]
Will do.

I've also run it with Node 18 and it runs fine, but there are some test warnings/failures. I'll have to look into those a bit more, to see whether the failures are caused by a change affecting the test harness or the actual code.
