### ISSUE TITLE
[Issue] Top code rows and documentation bar gets hidden behind the top grey menu bar 

### ISSUE THREAD

**Issue by joosbuijsNL** [pybricks/pybricks-code#161]
At some point during editing the top lines of the code terminal, and the top bar of the documentation pane, got hidden behind the top grey 'menu' bar. See image below. This makes it impossible to open the help menu to navigate to items.

I only recall pressing 'Backspace' with the documentation window active.
Reloading the page does not fix the issue.
Hide/show documentation does not fix the issue.

![image](https://user-images.githubusercontent.com/58334290/92961403-7635b580-f46f-11ea-8454-54abefea542c.png)

Chrome: Versie 84.0.4147.135 (Officiële build) (64-bits)
Windows 10

**Comment by BertLindeman** [comment]
Have seen this also sometimes.
I have no scenario to reproduce. 
Nor do I have a circumvention ater this situation occurs.

**Comment by joosbuijsNL** [comment]
Closing and re-opening the browser (and praying the code is still there) works.

**Comment by dlech** [comment]
Has anyone seen this problem recently? I think it might have been a bug in Chromium rather than Pybricks Code.

**Comment by BertLindeman** [comment]
Have not seen this lately. But to be honest I did not have enough time to do this.

**Comment by dlech** [comment]
Should be fixed now. See #214 for steps to reproduce the issue.
