### ISSUE TITLE
Display hub status indicator

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#173]
It may be useful to display:
- Which hub we are connected to:
   - Name
   - Type
- Battery level

Below is an example in a (very old) design exploration migrated from our previously internal issue tracker:

![image](https://user-images.githubusercontent.com/12326241/95563440-aa27da80-0a1d-11eb-8404-b041c7306ab4.png)

**Comment by dlech** [comment]
This has been implemented.
