### ISSUE TITLE
The state of this repo

### ISSUE THREAD

**Issue by SonicGamerEpisode55** [pybricks/pybricks-code#2274]
Why this repo is on ver 2.3.0-beta1 and the website is on ver 2.4.0-beta3? Is it because the stupid blocks thingy?

**Comment by BertLindeman** [comment]
There is a difference in the website code and the firmware to be installed onto the hubs,
as the about box shows for beta.pybricks.com:
```
MicroPython for LEGO® Powered Up smart hubs.

v3.4.0b2 (Pybricks Beta v2.4.0-beta.4)
```

and for code.pybricks.com:
```
MicroPython for LEGO® Powered Up smart hubs.

v3.3.0 (Pybricks Code v2.3.0)
```

or do I misunderstand your question?

Bert

**Comment by laurensvalk** [comment]
> Is it because the stupid blocks thingy?

It's a useful feature for a lot of people, but there's no need to use it if you prefer not to.
