### ISSUE TITLE
Web App crashes when trying to upload new program to InventorHub.

### ISSUE THREAD

**Issue by hirsche** [pybricks/pybricks-code#2294]
**Behavior:**
Web App is able to connect to the Hub. I can start the interactive shell and execute Python code. However, when trying to upload a new Python program, by pressing the "Play-Button", the app crashes. Side note: it crashes most of the time. Some times the upload works and the Python code executes on the Hub.

The enironment works fine for me on Windows (11), but I am currently switching to Fedora Linux where the Software does not work properly any more. Could you kindly assist! Bellow you find further details - if you'd need to know anything else, let me know!

Many thanks!!
Eduard

**Hub**: InventorHub (flashed with PyBricks Firmware on Windows)
**System:** Fedora 40 (Web App executes on that system)
**Browser:** Google Chrom Version 126.0.6478.114 (Official Build) (64-Bit)
**Error Text:** ChunkLoadError
**Stack Trace:**
ChunkLoadError
    at n.f.j (main.1bf60dfd.js:2:1662589)
    at main.1bf60dfd.js:2:1658083
    at Array.reduce (<anonymous>)
    at n.e (main.1bf60dfd.js:2:1658061)
    at 6938.beefce17.chunk.js:1:4061
    at N (main.1bf60dfd.js:2:1380738)
    at Al (main.1bf60dfd.js:2:1348027)
    at wc (main.1bf60dfd.js:2:1336659)
    at bc (main.1bf60dfd.js:2:1336631)
    at ic (main.1bf60dfd.js:2:1331653)
fs @ main.1bf60dfd.js:2
n.callback @ main.1bf60dfd.js:2
Bi @ main.1bf60dfd.js:2
El @ main.1bf60dfd.js:2
wl @ main.1bf60dfd.js:2
bl @ main.1bf60dfd.js:2
(anonymous) @ main.1bf60dfd.js:2
_c @ main.1bf60dfd.js:2
ic @ main.1bf60dfd.js:2
_ @ main.1bf60dfd.js:2
O @ main.1bf60dfd.js:2

**Then after some time:**
Failed to load resource: net::ERR_CONNECTION_RESET
An unknown error occurred when fetching the script.
TypeError: Failed to register a ServiceWorker for scope ('https://code.pybricks.com/') with script ('https://code.pybricks.com/service-worker.js'): An unknown error occurred when fetching the script.
(anonymous) @ main.1bf60dfd.js:2
pyodide.asm.js:1

**Comment by laurensvalk** [comment]
Thanks for reporting! Can you share the program that you're trying to run?

**Comment by hirsche** [comment]
Certainly, it's just a quickly coded snake game using the lights of the Inventor Hub and the Lego Controller (88010). Sorry, it is a bit messy and full of debug statements. The interesting thing: I continued working sending code to my Hub, but I am getting the problem much less often now.

```python
from pybricks.hubs import InventorHub
from pybricks.pupdevices import Remote, Motor, ColorSensor, UltrasonicSensor
from pybricks.parameters import Button, Color, Direction, Port, Side, Stop
from pybricks.robotics import DriveBase
from pybricks.tools import wait, StopWatch, Matrix
from urandom import randint

WIDTH = 5
HEIGHT = 5
SNAKE_HEAD = 1
SNAKE_BODY = 2
DOT = 3
SPEED = 1000
WAIT_BUTTON_PRESSED = 10

# initaliziere Hub und Fernbedienung
hub = InventorHub()
my_remote = Remote()


# Initialize the game state
snake = [(0, 0)]
direction = (0, 1)
dot = (randint(0, WIDTH-1), randint(0, HEIGHT-1))

# Function to draw the game state
def draw(hub, row, col):
    brightness = 0

    if (row, col) in snake:
        if (row, col) == snake[0]:
            # Draw snake head
            brightness = 100
        else:
            # Draw snake body            
            brightness = 40
    elif (row, col) == dot:
        # Draw dot
        brightness = 80

    hub.display.pixel(row, col, brightness)

def beep(hub):
    hub.speaker.beep()

beep(hub)
# Get user input
# Check which buttons are pressed.
pressed = my_remote.buttons.pressed()

# Main game loop
while True:
    # Draw the game state
    for row in range(HEIGHT):
        for col in range(WIDTH):
            draw(hub, row, col)
    
    pressed = my_remote.buttons.pressed()
    steps = int(SPEED/WAIT_BUTTON_PRESSED) + 1
    for i in range(steps):
        if len(pressed) == 0:
            pressed = my_remote.buttons.pressed()
        wait(WAIT_BUTTON_PRESSED)

    # Show the result.
    if Button.RIGHT_MINUS in pressed: # right
        direction = (0, 1)
        print("right")
    elif Button.RIGHT_PLUS in pressed: # left
        direction = (0, -1)
        print("left")
    elif Button.LEFT_PLUS in pressed: # up
        direction = (-1, 0)
        print("up")
    elif Button.LEFT_MINUS in pressed: # down
        direction = (1, 0)
        print("down")
    
    # Move the snake
    head = snake[0]
    new_head = (head[0] + direction[0], head[1] + direction[1])
    snake.insert(0, new_head)

    # Check if the snake has collided with the wall or itself
    if (
        new_head[0] < 0 or new_head[0] >= HEIGHT or
        new_head[1] < 0 or new_head[1] >= WIDTH or
        new_head in snake[1:]
    ):
        print("Game Over!")
        beep(hub)
        wait(100)
        beep(hub)
        break

    # Check if the snake has caught the dot
    if new_head == dot:
        # Generate a new dot
        dot = (randint(0, WIDTH-1), randint(0, HEIGHT-1))
    else:
        # Remove the tail of the snake
        snake.pop()

SystemExit()
```

**Comment by hirsche** [comment]
Strangly, it didn't occur anymore - for 30' now.

**Comment by BertLindeman** [comment]
Maybe strange idea: 
Could there be in the current environment more radio interference? 
WiFi and Bluetooth can use the same frequencies.

**Comment by hirsche** [comment]
Hmm, actually not that strange.

Lego uses Bluethooth LE, right? BLE could be quite susceptible to radio interference,  and indeed, I had at least 7-8 devices running over WiFi. Thus, this makes total sense.

However, as far as I know are most of them in the 5Gz radio spectrum and not in 2,4Gz anymore, where Bluethooth is sending.

**Comment by dlech** [comment]
> ChunkLoadError

This error has to do with loading `.js` files that contain part of the web app implementation.  It has nothing to do with Bluetooth.

There was probably a temporary network problem that went away.

---

For the curious: if you peek behind the scenes you can see the actual `.chunk.js` files. Likely one of this did not properly download the first time.

![image](https://github.com/pybricks/pybricks-code/assets/963645/014bc824-a24c-48c0-8e26-3af2c16f5d5e)

**Comment by hirsche** [comment]
@dlech you are right, the issue is not related to the bluetooth connection. I've been running the web app for couple of times and  "This error has to do with loading .js files that contain part of the web app implementation". The problem is that the web site itself seems to have performance issues. When connecting over a browser directly to "https://code.pybricks.com/" it is getting obvious. The application does crash because timeouts occure while fetching component code or similar from the server.
At first it only happened when uploading code to the hub but now I have the problem quite often, even when starting the application. The screen goes white, sometimes the app recovers but very often the "ChunkLoadError" occurs.

**Comment by laurensvalk** [comment]
Does it persist if you open the page in a new profile or private window? Or likewise, delete the site data and reload?

I wonder if it could continue to fail if it didn't load correctly the first time.

Once loaded properly, it should remain accessible offline.

**Comment by hirsche** [comment]
Yes, this persists if I am clearing the cache as well as using a private window - I've checked the network requests in the developer tool bar. Just for code.pybricks.com every request takes ages to download. My connection to the web seems  fine otherwise.
And once everything is downloaded everything works properly.

**Comment by laurensvalk** [comment]
Thanks for sharing that. Maybe we should switch to a different host.

Are you able to share which country your accessing it from? I might be able to ask our hosting provider why certain regions are experiencing slow service.

It might also help a lot if we made packaged up the docs so it would be requesting one zip file instead hundreds of small files.

**Comment by hirsche** [comment]
Hi guys,

I have to **apologize**! The problem occurred due to my network setup. Strangely, only some domains were slow when being accessed. Long story short: I have fixed everything and the connection to [PyBricks](https://code.pybricks.com) works perfectly fine now, and thus, the PWA.

Thanks for your support!
Eduard

**Comment by laurensvalk** [comment]
No worries! I am glad it is working now. Thank you for reporting.
