### ISSUE TITLE
While flashing, button is smaller

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#268]
![image](https://user-images.githubusercontent.com/12326241/105687891-473d4f00-5ef9-11eb-9388-2f29677d28c9.png)

The button is a bit smaller than the others.

`Version 88.0.4324.96 (Official Build) (64-bit)`

Ubuntu 20.04

**Comment by dlech** [comment]
Strange. The spinner and images are the same size (50x50). But for some reason, the `span.bp3-button-text` gets an extra 4 pixels vertically when it has the `img` element inside.
