### ISSUE TITLE
Duplicate vertical scroll bar shown with low height

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#407]
Chromium, Ubuntu 18.04. Only appears when there is at least some content in the terminal.

![image](https://user-images.githubusercontent.com/12326241/114752445-92c40400-9d56-11eb-812e-84639045f7e9.png)

**Comment by dlech** [comment]
Probably same as #406. Does the suggested fix work?

**Comment by laurensvalk** [comment]
Not sure how to find that.

![Screenshot from 2021-04-14 19-27-38](https://user-images.githubusercontent.com/12326241/114753274-91470b80-9d57-11eb-89b4-cd67e03f8526.png)

**Comment by dlech** [comment]
`<div class="layout-pane ...` above `<div class="pb-app-terminal-padding ...`

**Comment by laurensvalk** [comment]
Ah, so the search box only works when the element already selected.

Appears fixed that way, but might leave some whitespace below the scrollbar.
![image](https://user-images.githubusercontent.com/12326241/114754018-65785580-9d58-11eb-977d-3e72d9bef452.png)

**Comment by dlech** [comment]
That whitespace is expected/unrelated due to the fact that the terminal area can only be an interger multiple of the line height.
