### ISSUE TITLE
Coding canvas can stay white in dark mode

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#448]
This seems to happen on iOS Safari and its derivatives.

We don't support iOS right now because of the lack of Bluetooth support, but this might be a CSS issue we could fix one day.

This happens on both the stable and the beta release. On the beta release, the `BETA` text does not appear, so maybe it's an issue with the SVG?

![E0D3335D-C582-4F7F-A98A-EE421D953F69](https://user-images.githubusercontent.com/12326241/123378884-9b725b00-d58d-11eb-811d-95cb253dfa61.png)

**Comment by dlech** [comment]
Is this fixed now that we switched to Monaco?

**Comment by laurensvalk** [comment]
No; now it appears as if the editor isn't being loaded at all rather than in the wrong color. (I also can't type in it in light mode.)
