### ISSUE TITLE
Code editor does not load on iOS

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#469]
It appears as if the editor isn't being loaded at all on iOS. Tapping it does not bring up the keyboard.

_Originally posted by @laurensvalk in https://github.com/pybricks/pybricks-code/issues/448#issuecomment-875018670_

**Comment by dlech** [comment]
I don't have any real iOS devices, but it is working for me in the XCode Simulator tool.

**Comment by dlech** [comment]
Is this still a problem?

**Comment by laurensvalk** [comment]
No, it seems to work fine now.
