### ISSUE TITLE
Reduce import suggestions

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#471]
I'm not sure what's a good alternative yet, but these seem quite intrusive. They come up for just about anything you type.

https://user-images.githubusercontent.com/12326241/124714393-fdbe4a80-df01-11eb-961d-6c9d38f4bcc2.mp4

**Comment by dlech** [comment]
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#suggestontriggercharacters
