### ISSUE TITLE
Add left margin

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#472]
The code is pressed against the lefthand bar.

![image](https://user-images.githubusercontent.com/12326241/124715155-f481ad80-df02-11eb-9450-b225e45b8a91.png)

A bit of space would be nice. Here's the spacing in VS Code, though a bt less should still be fine.

![Screenshot from 2021-07-07 09-10-38](https://user-images.githubusercontent.com/12326241/124715493-5a6e3500-df03-11eb-91d5-ad887dcc0d12.png)

**Comment by dlech** [comment]
Actually, in VS Code, the gutter is just the same color as the text area - there is no other difference in layout. We could do the same. This would also make it easier to see the vertical indention lines (and possibly other decorations).

![image](https://user-images.githubusercontent.com/963645/124966751-44d33b00-dfe9-11eb-9d3e-7cbdd96aedfa.png)
