### ISSUE TITLE
Flashing firmware is slow (> 5 minutes)

### ISSUE THREAD

**Issue by dlech** [pybricks/pybricks-code#53]
Web Bluetooth does not support specifying write with response or write without response when writing to a GATT characteristic. For performance, we need to be able to write without response. The LEGO bootloader (on movehub, cityhub, cplushub) has set both `PROPERTY_WRITE_NO_RESPONSE` and `PROPERTY_WRITE` which causes Chrome on all platforms *except Android* to write with response. This results in an extra BLE packet being sent back from the hub to the host for every packet sent which really slows down the firmware flashing process.

**Comment by GianCann** [comment]
Just to say that also with this version of Chrome is required more than five minutes to flash the HUB, on Windows 10, 64 bit
Version 85.0.4174.0 (Official Build) canary (64 bit)

**Comment by dlech** [comment]
Control+ flashes in less than 2 minutes for me with the same specs (Win10 1909). What else could be different?

**Comment by GianCann** [comment]
I'm using Win 10 Pro 1709 with this USB BLE Adapter:
https://www.amazon.it/gp/product/B082HJFXFS

**Comment by GianCann** [comment]
I updated my desktop PC (Win10 Pro 1909) and still yet required >5 minutes to flash the HUB (about 8-10 minutes)
With my laptop (Win Home 1907) only about 2 minutes to complete the same operation
Same Chrome version

**Comment by dlech** [comment]
Chrome 85 has been in stable release for several months now, so closing.
