### ISSUE TITLE
Improve search engine preview

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#611]
There's a message about enabling Javascript. Maybe we can add a generic description somewhere.

![image](https://user-images.githubusercontent.com/12326241/135603347-facfe217-4c35-44b3-8b12-9d60c9fd65cc.png)

**Comment by dlech** [comment]
Google search in a new private window shows this for me:
![image](https://user-images.githubusercontent.com/963645/142471153-2c996f0e-c71e-454c-b589-6c8deac0d7fd.png)

**Comment by laurensvalk** [comment]
Yep, looks good now!
