### ISSUE TITLE
Include software licenses for included assets

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#673]
We have a display of the software licenses of Pybricks Code dependencies, but it seems that the firmware licenses are not included (aside from @pybricks/firmware top level license.)

They are included in the firmware ZIP archive, but I don't think we show those anywhere in the app.

Could we perhaps extract the required info and include them in the OSS license menu?

**Comment by laurensvalk** [comment]
If we want to get really detailed, there's the `pybricks-api` dependencies as well, such as LDraw.

**Comment by dlech** [comment]
The plan is to include accepting the firmware license when flashing firmware as described in https://github.com/pybricks/support/issues/173#issuecomment-812752509

**Comment by dlech** [comment]
> If we want to get really detailed, there's the `pybricks-api` dependencies as well, such as LDraw.

If the docs require additional notifications for license compliance (or if we just want to add a "credits" page), I think it should be kept integral to docs so that the online docs/pdfs/etc. include that as well.

**Comment by dlech** [comment]
Done in 85deb42.
