### ISSUE TITLE
Update message says new version of Pybricks *Beta* is available.

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#692]
This is a really minor issue, but I thought I'd mention it.

https://user-images.githubusercontent.com/12326241/146908573-6b00f6ca-b42d-4fbe-b72e-20fd3c829f55.mp4

**Comment by dlech** [comment]
What are the steps to reproduce the problem? This is expected if you are on https://beta.pybricks.com. The message uses the name of the current version of the app.

**Comment by laurensvalk** [comment]
Hmm, I thought I was on stable, but I must have been on beta, then.
