### ISSUE TITLE
Device does not show up under Linux-Chrome

### ISSUE THREAD

**Issue by harbaum** [pybricks/pybricks-code#754]
I see a rather odd issue. Using Chromium under Linux the City Hub in Bootloader mode is detected and can be flashed. But once flashed it simply does not show up. This only happens with chromium on Linux. Edge on Windows and Chrome on Android just work.

I see this with Chromium:
Version 98.0.4758.102 (Official Build) snap (64-bit)

**Comment by dlech** [comment]
Web Bluetooth is not officially supported on Linux, so there are a number of bugs like this that have to be manually worked around.  See https://github.com/pybricks/support/discussions/270 for some tips on how to manually remove devices and the cache file to try to get it working.

**Comment by harbaum** [comment]
Thanks a lot. Clearing the cache did the trick but not before restarting the bluetooth subsystem.
