### ISSUE TITLE
Template for new file (instead of hub selection)

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/pybricks-code#771]
When selecting a hub in the current version, I was thinking for a moment that this might do other things under the hood like restricting which hubs this program can run on.

So instead of choosing a hub, maybe we could call it "Choose a template"?

This can still include all the hubs, but also other things, like *None* (or maybe call it *Empty*).

I also added "Hub" to a few of the names here.

![image](https://user-images.githubusercontent.com/12326241/159234505-3e3d1d00-f43d-4cc2-927b-207ffadfa635.png)

**Comment by laurensvalk** [comment]
And in terms of hub names, here's another variant:

![image](https://user-images.githubusercontent.com/12326241/159236789-666df1a5-a106-4000-8123-da910f4acf30.png)

**Comment by BertLindeman** [comment]
Just a idea.

Would `ThisHub` be a good candidate for a template here?

It might be causing confusion and add unneeded complexity.

I like the idea to add the images of the hubs.

**Comment by laurensvalk** [comment]
Pictures can be provided by https://github.com/pybricks/pybricks-api/issues/100 so we'll have transparent backgrounds.
